
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author mustafa
 */
public class SellProject extends javax.swing.JFrame {
    DBHandlerSellProject dbhSellProject = new DBHandlerSellProject(); //veritabanı üzerinde işlem yapılabilmesi için oluşturulan dbhSellProject objesi
    
    /**
     * Creates new form SellProject
     */
    public SellProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelProjeSatis = new keeptoo.KGradientPanel();
        txtSellTime = new javax.swing.JTextField();
        labelSellDate = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        labelSellPeriod = new javax.swing.JLabel();
        btnSellProject = new javax.swing.JButton();
        labelCustomers = new javax.swing.JLabel();
        labelSellTime = new javax.swing.JLabel();
        radioDay = new javax.swing.JRadioButton();
        radirMonth = new javax.swing.JRadioButton();
        radioYear = new javax.swing.JRadioButton();
        labelProjects = new javax.swing.JLabel();
        labelPrice = new javax.swing.JLabel();
        cbCustomers = new javax.swing.JComboBox();
        cbProjects = new javax.swing.JComboBox();
        dpSellDate = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proje Satış İşlemleri");
        setSize(new java.awt.Dimension(280, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelProjeSatis.setkEndColor(new java.awt.Color(168, 168, 255));
        panelProjeSatis.setkGradientFocus(0);
        panelProjeSatis.setkStartColor(new java.awt.Color(226, 226, 255));

        txtSellTime.setPreferredSize(null);

        labelSellDate.setText("Satış Tarihi:");
        labelSellDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtPrice.setPreferredSize(null);

        labelSellPeriod.setText("Satış Periyodu:");
        labelSellPeriod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnSellProject.setText("Proje Satış");
        btnSellProject.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSellProject.setPreferredSize(null);
        btnSellProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellProjectActionPerformed(evt);
            }
        });

        labelCustomers.setText("Şirketler:");
        labelCustomers.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        labelSellTime.setText("Satış Süresi:");
        labelSellTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        buttonGroup1.add(radioDay);
        radioDay.setText("Gün");
        radioDay.setPreferredSize(null);

        buttonGroup1.add(radirMonth);
        radirMonth.setText("Ay");
        radirMonth.setPreferredSize(null);

        buttonGroup1.add(radioYear);
        radioYear.setText("Yıl");
        radioYear.setPreferredSize(null);
        radioYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYearActionPerformed(evt);
            }
        });

        labelProjects.setText("Projeler:");
        labelProjects.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        labelPrice.setText("Fiyat:");
        labelPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cbCustomers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Şirketler..." }));

        cbProjects.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Projeler..." }));

        dpSellDate.setPreferredSize(null);

        javax.swing.GroupLayout panelProjeSatisLayout = new javax.swing.GroupLayout(panelProjeSatis);
        panelProjeSatis.setLayout(panelProjeSatisLayout);
        panelProjeSatisLayout.setHorizontalGroup(
            panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjeSatisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelSellPeriod)
                        .addComponent(labelSellTime, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(labelPrice)
                    .addComponent(labelSellDate)
                    .addComponent(labelProjects)
                    .addComponent(labelCustomers))
                .addGap(18, 18, 18)
                .addGroup(panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSellProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelProjeSatisLayout.createSequentialGroup()
                        .addComponent(radioDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radirMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtSellTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCustomers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbProjects, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dpSellDate, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panelProjeSatisLayout.setVerticalGroup(
            panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjeSatisLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustomers)
                    .addComponent(cbCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProjects, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(labelProjects))
                .addGap(16, 16, 16)
                .addGroup(panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSellDate)
                    .addComponent(dpSellDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radirMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSellPeriod))
                .addGap(18, 18, 18)
                .addGroup(panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSellTime, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(labelSellTime))
                .addGap(18, 18, 18)
                .addGroup(panelProjeSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(labelPrice))
                .addGap(18, 18, 18)
                .addComponent(btnSellProject, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProjeSatis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProjeSatis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Form üzerinde bulunan combobox elemanlarına müştelerin ve projelerin bilgilerinin yüklenmesini sağlayan metod
    public void showCompaniesAndProjets(){
        
        Vector model = new Vector();
        
        model = dbhSellProject.getCompanies();
        cbCustomers.setModel(new DefaultComboBoxModel(model));
        
        model = dbhSellProject.getProject();
        cbProjects.setModel(new DefaultComboBoxModel(model));
    }
    
    //Swing elemanlarının içeriklerinin temizlenmesi
    public void clearItems(){
        txtPrice.setText("");
        txtSellTime.setText("");
        dpSellDate.setDateToToday();
        buttonGroup1.clearSelection();
        cbProjects.setSelectedIndex(0);
        cbCustomers.setSelectedIndex(0);
    }
    
    private void btnSellProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellProjectActionPerformed
        // TODO add your handling code here:
        CustomerInfo customerInfoScreen = new CustomerInfo();
        String period = null;
        
        // Swing elemanlarının içerik kontrolünün yapılması
        if(txtPrice.equals("") || txtSellTime.equals("") || (!radirMonth.isSelected() && !radioDay.isSelected() && !radioYear.isSelected())){
            JOptionPane.showMessageDialog(this, "Alanlar boş bırakılmamalıdır!");
        }
        
        else{
            
            if(radioDay.isSelected())
                period = "Gün";
                
            else if(radirMonth.isSelected())
                period = "Ay";
            
            else if(radioYear.isSelected())
                period = "Yıl";
            
            else
                JOptionPane.showMessageDialog(this, "Periyot boş bırakılamaz!", "Warning", JOptionPane.WARNING_MESSAGE);
        
            int technicalSuppotTime = Integer.parseInt(txtSellTime.getText());
            
            int price = Integer.parseInt(txtPrice.getText());
            String sellDate = dpSellDate.getDate().toString();
            
            Customer customer = (Customer)cbCustomers.getSelectedItem();
            int customeriId = customer.getMusteriId();
            
            Project project = (Project)cbProjects.getSelectedItem();
            int projectId = project.getProjectId();
            
            //Swing elemanlarından alınan değerlerin SellProject() metoduna parametre olara gönderilmesi
            if(dbhSellProject.SellProject(customeriId, projectId, sellDate, technicalSuppotTime, period, price)){//metoddan true değer dönmesini durumunda
                JOptionPane.showMessageDialog(this, "Satış işlemi başarılı.", "Message", JOptionPane.INFORMATION_MESSAGE);
                
                int dialog;
                //Ana ekrana dönmek istiyor musunuz? sorunusu soran ve Yes/No butonlarıyle cevap alan dialog ekranı
                dialog = JOptionPane.showConfirmDialog(this, "Ana ekrana dönmek istiyor musunuz?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                
                if(dialog == JOptionPane.YES_OPTION){//Yes butonuna basılması durumu
                    
                    this.setVisible(false);
                    customerInfoScreen.setVisible(true);
                }
                else{//No butonuna basılması durumu
                    clearItems(); //Yeni satış işlemleri için swing elemanlarının içeriklerinin temizler
                }
                
            }else{//metoddan false değer dönmesi durumu
                JOptionPane.showMessageDialog(this, "Satış işleminde hata oluştu!", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSellProjectActionPerformed

    private void radioYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioYearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        showCompaniesAndProjets();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellProject().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSellProject;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbCustomers;
    private javax.swing.JComboBox cbProjects;
    private com.github.lgooddatepicker.components.DatePicker dpSellDate;
    private javax.swing.JLabel labelCustomers;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelProjects;
    private javax.swing.JLabel labelSellDate;
    private javax.swing.JLabel labelSellPeriod;
    private javax.swing.JLabel labelSellTime;
    private keeptoo.KGradientPanel panelProjeSatis;
    private javax.swing.JRadioButton radioDay;
    private javax.swing.JRadioButton radioYear;
    private javax.swing.JRadioButton radirMonth;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSellTime;
    // End of variables declaration//GEN-END:variables
}
