
import javax.swing.JOptionPane;


/**
 *
 * @author mustafa
 */
public class UpdateCustomer extends javax.swing.JFrame {

     DBHandlerCustomer dbhCustomer = new DBHandlerCustomer(); //veritabanı üzerinde işlemlerin yapılabilmesi için dbhCustomer objesinin oluşturulması
    /**
     * Creates new form UpdateCustomer
     */
    public UpdateCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        txtPhone = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtCustomerName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        labelMusteriAdi = new javax.swing.JLabel();
        labelAdres = new javax.swing.JLabel();
        labelTelefon = new javax.swing.JLabel();
        btnCustomerInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Müşteri Güncelle");
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(168, 168, 255));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(226, 226, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(300, 250));

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnUpdate.setText("Güncelle");
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setPreferredSize(new java.awt.Dimension(75, 23));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtCustomerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelMusteriAdi.setText("Müşteri Adı:");
        labelMusteriAdi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        labelAdres.setText("Adres:");
        labelAdres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        labelTelefon.setText("Telefon:");
        labelTelefon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnCustomerInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCustomerInfo.setText("Müşteri İşlemleri");
        btnCustomerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAdres, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTelefon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelMusteriAdi, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPhone)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(btnCustomerInfo)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMusteriAdi))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAdres))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefon))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        //CustomerInfoda bulunan static değişkenler sayesinde swing elemanlarına yazılan değerlerin
        //değişkenlere atanması
        int id = CustomerInfo.updateCustomerId;
        String customerName = txtCustomerName.getText();
        String address = txtAddress.getText();
        String phone = txtPhone.getText();
        
        //Swing elemanlarının boş olup olmadığının kontrolünün yapılması ve kullanıcının uyarılması
        if(txtCustomerName.getText().isEmpty() || txtAddress.getText().isEmpty() || txtPhone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Lütfen boş alanları doldurun!", "HATA!", ERROR);
        }
        else{//swing elemanları boş değilse 
            if(dbhCustomer.updateCustomer(id, customerName, address, phone)){//updateCustomer() metoduna veriler parametre olarak gönderilir ve true dönerse koşul sağlanır
                
                JOptionPane.showMessageDialog(this, "Güncelleme işlemi başarılı.", "Message", JOptionPane.INFORMATION_MESSAGE);
                
                int dialogButton;
                //Ana ekrana dönmek istiyor musunuz? sorusunu soran ve Yes/No butonlarıyla cevapları alan dialog ekranı
                dialogButton = JOptionPane.showConfirmDialog(this, "Ana ekrana dönmek istiyor musunuz?", "Onay Gerekiyor", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                
                if(dialogButton == JOptionPane.YES_OPTION){//Dialogtan Yes cevabı gelirse Müşteri işlemleri ekranına geçiş yapılır
                    this.setVisible(false);
                    CustomerInfo customerInfoScreen = new CustomerInfo();
                    customerInfoScreen.setVisible(true);
                }
            }
            else{//updateCustomer() metodunda false değer dönmesi durumu
                JOptionPane.showMessageDialog(this, "Güncelleme işlemi başarısız!", "HATA!", ERROR);
            }
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    //Form açıldığında CustomerInfo sınıfında bulunan static değişkenler yardımıyla 
    //jTable üzerinde seçilen müşterilerin bilgilerinin UpdateCustomer(Müşteri Güncelle)
    //ekranındaki swing elemanlarına yazılması
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtCustomerName.setText(CustomerInfo.updateCustomerName);
        txtAddress.setText(CustomerInfo.updateAddress);
        txtPhone.setText(CustomerInfo.updatePhone);
    }//GEN-LAST:event_formWindowOpened

    //Müşteri İşlemleri Butonu
    private void btnCustomerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerInfoActionPerformed
        // TODO add your handling code here:
        //Müşteri Güncelle ekranı kapatır ve Müşteri işlemleri ekranını açar
        CustomerInfo customerInfo = new CustomerInfo();
        CustomerInfo.clearItems();//ekranı kapatmadan önce CustomerInfo(Müşteri işlemleri) sınıfına ait static değişkenlerin siler.
        setVisible(false);
        customerInfo.setVisible(true);
    }//GEN-LAST:event_btnCustomerInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerInfo;
    private javax.swing.JButton btnUpdate;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelAdres;
    private javax.swing.JLabel labelMusteriAdi;
    private javax.swing.JLabel labelTelefon;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
